catagories:
  1Seviye-Kufur:
    wordlist:
      - amk
      - aq
      - yarram
      - yarrak
      - yarra
      - yarrağımı
      - yarragımı
      - penis
      - pezevek
      - pezeven
      - pezeveng
      - pezevengi
      - pezevengin evladı
      - pezevenk
      - taaklarn
      - amcık
      - amcik
      - taaklarna
      - tarrakimin
      - tasak
      - tassak
      - taşak
      - taşşak
      - amina koyim
      - amina
      - cocuğu
      - cocu
    punishment: tempmute %player% 45m [OTO MUTE] 1. Seviye Küfür
  2Seviye-Kufur:
    wordlist:
      - orospu
      - orosp
      - oros
      - babanı sikeyim
      - babanı
      - anneni
      - anan
      - anne
      - skyim
      - slaleni
      - sokam
      - sikerim
      - sokarım
      - sokarim
      - sokarm
      - sokarmkoduumun
      - sokayım
      - sokaym
      - sokiim
      - soktuğumunun
      - sokuk
      - sokum
      - sokuş
      - sokuyum
      - soxum
      - babani sikeyim
      - sikeyim
      - sikerim
      - sikik
      - sokuk
      - babaanneni
      - babaneni
      - bacını
      - sik
      - siksin
      - sikiş
      - karını
      - kızını
      - domal
      - götünü
      - anan
      - anandan
      - anandan
      - anandan
      - anandan
      - ananı
      - ananı
      - ananın
      - anana
      - ananın am
      - ananın amı
      - ananın dölü
      - ananınki
      - ananısikerim
      - ananı sikerim
      - ananısikeyim
      - ananı sikeyim
      - ananızın
      - ananızın am
      - anani
      - ananin
      - ananisikerim
      - anani sikerim
      - ananisikeyim
      - anani sikeyim
      - anann
      - ananz
      - anas
      - anasını
      - anasının am
      - anası orospu
      - anasi
      - anasinin
      - anay
      - anayin
      - angut
      - anneni
      - annenin
      - annesiz
      - anuna
      - aptal
    punishment: tempmute %player% 2h [OTO MUTE] 2. Seviye Küfür
  Argo-Kufur:
    wordlist:
      - mal
      - aptal
      - salak
      - gerzek
      - göt
      - ibne
      - ibine
      - kaşar
      - gavat
      - pipi
    punishment: tempmute %player% 30m [OTO MUTE] Argo Kullanımı
  Dini-Kufur:
    wordlist:
      - allahını
      - allahini
      - peygamberini
      - islamini
      - allahsız
      - islamını
      - am*
    punishment: tempmute %player% 30m [OTO MUTE] Argo Kullanımı

whitelist-words:
  - ancak
  - ama
  - amca
  - ampul
  - aman
  - amasya
  - amiral
  - amaç
  - amaçlama
  - amigo

webhook:
  enabled: false
  url: "YOUR WEBHOOK"

censor:
  chance: 1.0

administrator:
  permissions: poenasaga_yetkili
